const projects=[
 {number:"01",type:"Web Application",title:"Accounting & Finance System",desc:"A complete Django system for transactions, budgets, cash flow, and financial reporting.",tags:["Django","Python","Bootstrap"],tone:"mint"},
 {number:"02",type:"Desktop Application",title:"Mini Supermarket POS",desc:"A practical point-of-sale experience with product, category, cart, and sales management.",tags:["C#","WinForms","SQL Server"],tone:"violet"},
 {number:"03",type:"E-commerce",title:"MotoShop Cambodia",desc:"A modern motorcycle storefront with products, cart, authentication, orders, and an admin panel.",tags:["Laravel","MySQL","PHP"],tone:"amber"}];
document.querySelector("#projects").innerHTML=projects.map(p=>`<article class="project ${p.tone}"><div class="projectVisual"><span>${p.number}</span><div class="window"><i></i><i></i><i></i><div class="windowContent"><b>${p.title.split(" ")[0]}</b><small>Dashboard • Management • Reports</small></div></div></div><div class="projectBody"><small>${p.type}</small><h3>${p.title}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join("")}</div><a href="#contact">View case study <b>↗</b></a></div></article>`).join("");
const skills=[["Frontend","HTML / CSS",92],["Frontend","JavaScript",78],["Backend","Python / Django",85],["Backend","PHP / Laravel",82],["Application","C# / WinForms",88],["Creative","Photography",94]];
document.querySelector("#skillGrid").innerHTML=skills.map(s=>`<div class="skill"><small>${s[0]}</small><div><b>${s[1]}</b><span>${s[2]}%</span></div><progress max="100" value="${s[2]}"></progress></div>`).join("");
const theme=document.querySelector("#theme");theme.addEventListener("click",()=>{const dark=document.documentElement.dataset.theme==="dark";document.documentElement.dataset.theme=dark?"light":"dark";theme.textContent=dark?"☾":"☼"});
const menu=document.querySelector("#menu"),links=document.querySelector("#navLinks");menu.addEventListener("click",()=>{links.classList.toggle("open");menu.textContent=links.classList.contains("open")?"×":"☰"});links.addEventListener("click",()=>{links.classList.remove("open");menu.textContent="☰"});
